input_data_path: "data/raw/heart.csv"
input_model_path: "ml_project/models/model.pkl"
output_predict_path: "ml_project/models/prediction.csv"
splitting_params:
  val_size: 0.1
  random_state: 42
predict_params:
  model_type: "RandomForestClassifier"
  #model_type: "LogisticRegression"
  #model_type: "KNeighborsClassifier"
  random_state: 42
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "thal"
    - "ca"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "target"
